//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPK_ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attendance_Header()
        {
            this.Attendance_Detail = new HashSet<Attendance_Detail>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> RowIDEmployee { get; set; }
        public Nullable<System.DateTime> AttendanceShortDate { get; set; }
        public Nullable<double> TotalWorkingHours { get; set; }
        public Nullable<double> TotalWorkingMinutes { get; set; }
        public Nullable<double> TotalWorkingSeconds { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsBlock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance_Detail> Attendance_Detail { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
