//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPK_ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Detail
    {
        public int RowID { get; set; }
        public Nullable<int> RowIDAttendanceHeader { get; set; }
        public Nullable<int> RowIDEmployee { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int RowIDAttendanceReason { get; set; }
        public string Reason { get; set; }
        public Nullable<int> RowIDEmployeeEdited { get; set; }
        public Nullable<int> RowIDEmployeeCreated { get; set; }
    
        public virtual AttendanceReason AttendanceReason { get; set; }
        public virtual Attendance_Header Attendance_Header { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
