//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPK_ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department_Category()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public int RowID { get; set; }
        public string DepartmentCategoryName { get; set; }
        public string DepartmentCategoryNameEnglish { get; set; }
        public string DepartmentCategoryCode { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string DepartmentCategoryCodeOld { get; set; }
        public string IsShowVAM { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Images { get; set; }
        public string Alias { get; set; }
        public string SmallDescription { get; set; }
        public string Description { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
    }
}
