//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPK_ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Employee_Category = new HashSet<Employee_Category>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> RowIDDepartmentCategory { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentNameEnglish { get; set; }
        public string DepartmentShortName { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> AliasNumber { get; set; }
        public string DepartmentTitleBoard { get; set; }
        public string DepartmentDescription { get; set; }
        public string DepartmentPhoneNumber { get; set; }
        public string DepartmentEmail { get; set; }
        public string DepartmentAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.DateTime> LastActiveDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string IsDelete { get; set; }
        public string IsActive { get; set; }
    
        public virtual Department_Category Department_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Category> Employee_Category { get; set; }
    }
}
