//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPK_ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Employee_Category
    {
        public int RowID { get; set; }
        public Nullable<int> RowIDEmployeeCategory { get; set; }
        public Nullable<int> RowIDEmployee { get; set; }
    
        public virtual Employee_Category Employee_Category { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
