//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPK_ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overtime
    {
        public int RowID { get; set; }
        public Nullable<int> RowIDEmployee { get; set; }
        public Nullable<double> TotalHour { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RowIDEmployeeApprove { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Reason { get; set; }
    }
}
