//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPK_ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int RowID { get; set; }
        public Nullable<decimal> SalaryValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RowIDEmployees { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
